/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas1pemvis;

import javax.swing.JOptionPane;

/**  
 *
 * @author 62813
 */
public class m2soal2 extends javax.swing.JFrame {

    /**
     * Creates new form m2soal2
     */
    public m2soal2() {
        initComponents();
        angka.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pesanan = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        jumlah = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        hapus = new javax.swing.JButton();
        beli = new javax.swing.JButton();
        kurang = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        angka = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        menu10 = new javax.swing.JRadioButton();
        menu9 = new javax.swing.JRadioButton();
        menu8 = new javax.swing.JRadioButton();
        menu7 = new javax.swing.JRadioButton();
        menu6 = new javax.swing.JRadioButton();
        menu5 = new javax.swing.JRadioButton();
        menu4 = new javax.swing.JRadioButton();
        menu3 = new javax.swing.JRadioButton();
        menu2 = new javax.swing.JRadioButton();
        menu1 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(154, 165, 54));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        jLabel9.setText("MENU");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel9)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel10.setText("---------------------------------");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        jLabel4.setText("INFORMASI PESANAN");

        jLabel5.setText("Pesanan Anda   :");

        jLabel6.setText("Harga                :");

        jLabel7.setText("Jumlah Pesanan :");

        jLabel8.setText("Total                  :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(pesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(jumlah)
                            .addComponent(harga))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 270, 190));

        hapus.setText("HAPUS");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, -1, -1));

        beli.setText("BELI");
        beli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliActionPerformed(evt);
            }
        });
        getContentPane().add(beli, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, -1, -1));

        kurang.setText("-");
        kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangActionPerformed(evt);
            }
        });
        getContentPane().add(kurang, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, -1, -1));

        tambah.setText("+");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, -1));
        getContentPane().add(angka, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 120, 40));

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 3, 18)); // NOI18N
        jLabel3.setText("JUMLAH BELI");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, -1));

        menu.add(menu10);
        menu10.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        menu10.setText("Es Nutrisari");
        getContentPane().add(menu10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        menu.add(menu9);
        menu9.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        menu9.setText("Es Marimas");
        menu9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu9ActionPerformed(evt);
            }
        });
        getContentPane().add(menu9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, -1));

        menu.add(menu8);
        menu8.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        menu8.setText("Es Jeruk");
        getContentPane().add(menu8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

        menu.add(menu7);
        menu7.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        menu7.setText("Teh Anget");
        getContentPane().add(menu7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        menu.add(menu6);
        menu6.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        menu6.setText("Es Teh");
        getContentPane().add(menu6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        menu.add(menu5);
        menu5.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        menu5.setText("Rawon");
        getContentPane().add(menu5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        menu.add(menu4);
        menu4.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        menu4.setText("Soto Ayam");
        getContentPane().add(menu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        menu.add(menu3);
        menu3.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        menu3.setText("Nasi Rames");
        getContentPane().add(menu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        menu.add(menu2);
        menu2.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        menu2.setText("Nasi Kuning");
        getContentPane().add(menu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        menu.add(menu1);
        menu1.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        menu1.setText("Nasi Campur");
        getContentPane().add(menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 3, 18)); // NOI18N
        jLabel2.setText("WARUNG MAKAN WULAN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas1pemvis/Random (1).jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu9ActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        menu.clearSelection();
        angka.setText("0");
        pesanan.setText("");
        jumlah.setText("");
        harga.setText("");
        total.setText("");
    }//GEN-LAST:event_hapusActionPerformed

    private void beliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliActionPerformed
        // TODO add your handling code here:
        String Pesanan = "";
        int Harga = 0;
        boolean menuDipilih = false;

        
        if(menu1.isSelected()){
            Pesanan = " Nasi Campur";
            Harga = 10000;
            menuDipilih = true;
        }else if (menu2.isSelected()){
            Pesanan = " Nasi Kuning";
            Harga = 12000;
            menuDipilih = true;
        }else if (menu3.isSelected()){
            Pesanan = " Nasi Rames";
            Harga = 15000;
            menuDipilih = true;
        }else if (menu4.isSelected()){
            Pesanan = " Soto Ayam";
            Harga = 13000;
            menuDipilih = true;
        }else if (menu5.isSelected()){
            Pesanan = "Rawon";
            Harga = 16000;
            menuDipilih = true;
        }else if (menu6.isSelected()){
            Pesanan = "Es Teh";
            Harga = 4000;
            menuDipilih = true;
        }else if (menu7.isSelected()){
            Pesanan = "Teh Anget";
            Harga = 5000;  
            menuDipilih = true;
        }else if (menu8.isSelected()){
            Pesanan = "Es Jeruk";
            Harga = 6000;  
            menuDipilih = true;
        }else if (menu9.isSelected()){
            Pesanan = "Es Marimas";
            Harga = 2000;
            menuDipilih = true;
        }else if (menu10.isSelected()){
            Pesanan = "Es Nutrisari";
            Harga = 5000;
            menuDipilih = true;
        }
        
        int Jumlah = Integer.parseInt(angka.getText());

    if (menuDipilih && Jumlah > 0) {
        int eHarga = Harga * Jumlah;
        total.setText("Rp." + eHarga);
        pesanan.setText(Pesanan);
        harga.setText("Rp" + Integer.toString(eHarga)); 
        jumlah.setText(Integer.toString(Jumlah));
    } else {
        JOptionPane.showMessageDialog(null, "Pilih menu terlebih dahulu", "Peringatan", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_beliActionPerformed

    private void kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangActionPerformed
        // TODO add your handling code here:
        int Jumlah = Integer.parseInt(angka.getText());
        Jumlah--;
        angka.setText(Integer.toString(Jumlah));
    }//GEN-LAST:event_kurangActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        int Jumlah = Integer.parseInt(angka.getText());
        Jumlah++;
        angka.setText(Integer.toString(Jumlah));
    }//GEN-LAST:event_tambahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(m2soal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(m2soal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(m2soal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(m2soal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new m2soal2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField angka;
    private javax.swing.JButton beli;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jumlah;
    private javax.swing.JButton kurang;
    private javax.swing.ButtonGroup menu;
    private javax.swing.JRadioButton menu1;
    private javax.swing.JRadioButton menu10;
    private javax.swing.JRadioButton menu2;
    private javax.swing.JRadioButton menu3;
    private javax.swing.JRadioButton menu4;
    private javax.swing.JRadioButton menu5;
    private javax.swing.JRadioButton menu6;
    private javax.swing.JRadioButton menu7;
    private javax.swing.JRadioButton menu8;
    private javax.swing.JRadioButton menu9;
    private javax.swing.JTextField pesanan;
    private javax.swing.JButton tambah;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
