/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas1pemvis;

import javax.swing.JOptionPane;

/**
 *
 * @author 62813
 */
public class soal1m2 extends javax.swing.JFrame {

    /**
     * Creates new form soal1m2
     */
    public soal1m2() {
        initComponents();
        ttarif.setText("10000");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        reset = new javax.swing.JButton();
        tgajibersih = new javax.swing.JTextField();
        tgajibruto = new javax.swing.JTextField();
        ttarif = new javax.swing.JTextField();
        tjumlah = new javax.swing.JTextField();
        btotal = new javax.swing.JButton();
        bhitung = new javax.swing.JButton();
        lgajibersih = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lgajibruto = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ltarif = new javax.swing.JLabel();
        ljumlah = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, -1, -1));

        tgajibersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgajibersihActionPerformed(evt);
            }
        });
        jPanel1.add(tgajibersih, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 100, -1));
        jPanel1.add(tgajibruto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 100, -1));
        jPanel1.add(ttarif, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 100, -1));

        tjumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tjumlahActionPerformed(evt);
            }
        });
        jPanel1.add(tjumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 100, -1));

        btotal.setText("Total");
        btotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btotalActionPerformed(evt);
            }
        });
        jPanel1.add(btotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, -1, -1));

        bhitung.setText("Hitung Gaji");
        bhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhitungActionPerformed(evt);
            }
        });
        jPanel1.add(bhitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, -1));

        lgajibersih.setText("Gaji Bersih :");
        jPanel1.add(lgajibersih, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jLabel8.setText("==================");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        lgajibruto.setText("Gaji Bruto :");
        jPanel1.add(lgajibruto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel6.setText("==================");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        ltarif.setText("Tarif Per - Jam :");
        jPanel1.add(ltarif, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        ljumlah.setText("Jumlah Jam Kerja 1 Minggu :");
        jPanel1.add(ljumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("-------------------------");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        jLabel2.setText("MENGHITUNG GAJI");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas1pemvis/Background aesthetic (1).jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(443, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tjumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tjumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tjumlahActionPerformed

    private void tgajibersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgajibersihActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgajibersihActionPerformed

    private void bhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhitungActionPerformed
        // TODO add your handling code here:
       double gajiBruto;

    // Validasi input untuk jamKerja
    String jamKerja1 = tjumlah.getText();
    if (jamKerja1.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Jam kerja harus diisi.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
    } else {
        double jamKerja = Double.parseDouble(jamKerja1);

    if (jamKerja < 0) {
        // Tampilkan pesan kesalahan jika angka negatif
        JOptionPane.showMessageDialog(this, "Jam kerja harus bilangan positif.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
    } else {
        String tarifStr = ttarif.getText();
        if (tarifStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tarif harus diisi.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        } else {
            double tarif = Double.parseDouble(tarifStr);

            if (jamKerja <= 40) {
                gajiBruto = jamKerja * tarif;
            } else {
                double jamLembur = jamKerja - 40;
                gajiBruto = (40 * tarif) + (jamLembur * (1.5 * tarif));
            }

    // Set nilai gaji bruto ke komponen teks eGajiBruto
        tgajibruto.setText(String.valueOf(gajiBruto));
     }
    }
    }
    }//GEN-LAST:event_bhitungActionPerformed

    private void btotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btotalActionPerformed
        // TODO add your handling code here:
        double GajiBruto = Double.parseDouble(tgajibruto.getText());
        
        double PotonganPajak = 0.10 * GajiBruto;
        
        double GajiBersih = GajiBruto - PotonganPajak;
        
        tgajibersih.setText(String.valueOf(GajiBersih));
    }//GEN-LAST:event_btotalActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        tjumlah.setText("");
        ttarif.setText("");
        tgajibruto.setText("");
        tgajibersih.setText("");
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(soal1m2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(soal1m2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(soal1m2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(soal1m2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new soal1m2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bhitung;
    private javax.swing.JButton btotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lgajibersih;
    private javax.swing.JLabel lgajibruto;
    private javax.swing.JLabel ljumlah;
    private javax.swing.JLabel ltarif;
    private javax.swing.JButton reset;
    private javax.swing.JTextField tgajibersih;
    private javax.swing.JTextField tgajibruto;
    private javax.swing.JTextField tjumlah;
    private javax.swing.JTextField ttarif;
    // End of variables declaration//GEN-END:variables
}
